
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 19 19:47:14 ART 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENCABEZADO = 6;
  public static final int SALTO_DE_LINEA = 4;
  public static final int SANGRIA = 8;
  public static final int INICIO = 10;
  public static final int FIN = 11;
  public static final int EOF = 0;
  public static final int PALABRA = 12;
  public static final int CURSIVA = 3;
  public static final int ITEM_NUMERICO = 2;
  public static final int error = 1;
  public static final int NEGRITA = 5;
  public static final int ITEM = 7;
  public static final int NEGRITA_CURSIVA = 9;
}

