
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 19 23:23:31 ART 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENCABEZADO = 8;
  public static final int SALTO_DE_LINEA = 6;
  public static final int SANGRIA = 10;
  public static final int EOF = 0;
  public static final int PALABRA = 12;
  public static final int SIGNO = 3;
  public static final int ESPACIO = 2;
  public static final int CURSIVA = 5;
  public static final int ITEM_NUMERICO = 4;
  public static final int error = 1;
  public static final int NEGRITA = 7;
  public static final int ITEM = 9;
  public static final int NEGRITA_CURSIVA = 11;
}

