
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 24 15:50:02 ART 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TEXTO = 14;
  public static final int ENCABEZADO = 10;
  public static final int TITULO = 5;
  public static final int SALTO_DE_LINEA = 8;
  public static final int SANGRIA = 12;
  public static final int EOF = 0;
  public static final int SIGNO = 3;
  public static final int ESPACIO = 2;
  public static final int CURSIVA = 6;
  public static final int URL = 7;
  public static final int ITEM_NUMERICO = 4;
  public static final int error = 1;
  public static final int NEGRITA = 9;
  public static final int ITEM = 11;
  public static final int NEGRITA_CURSIVA = 13;
}

